/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Comprador;
import Modelo.Conexion;
import Persistencia.CompradorData;
import Persistencia.PeliculaData;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Usuario
 */
public class compradorVista extends javax.swing.JInternalFrame {

    private SistemaCine sc = new SistemaCine();
    Conexion conex = sc.conexionDb();
    CompradorData compradorDAO = new CompradorData(conex);

    DefaultTableModel modeloTableComprador;
    TableRowSorter<DefaultTableModel> sortModelComprador;

    private void llenarTableCompradores() {

        DocumentListener listenerFiltro = new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                filtrarCompradores();
            }

            public void removeUpdate(DocumentEvent e) {
                filtrarCompradores();
            }

            public void changedUpdate(DocumentEvent e) {
                filtrarCompradores();
            }
        };
        CompradorData compradorDAO = new CompradorData(conex);
        List<Comprador> listaCompradores = compradorDAO.listarCompradores();

        tableCompradores.setShowGrid(false);
        modeloTableComprador = (DefaultTableModel) tableCompradores.getModel();
        modeloTableComprador.setRowCount(0);

        for (Comprador c : listaCompradores) {
            modeloTableComprador.addRow(new Object[]{
                c.getIdComprador(),
                c.getNombre(),
                c.getDni(),
                c.getFechaNac(),
                c.getMedioPago()
            });
        }

        sortModelComprador = new TableRowSorter<>(modeloTableComprador);
        tableCompradores.setRowSorter(sortModelComprador);
        txtIDComprador.getDocument().addDocumentListener(listenerFiltro);
    }

    private void filtrarCompradores() {
        String txtComprador = txtIDComprador.getText().trim();
        if (txtComprador.isEmpty()) {
            sortModelComprador.setRowFilter(null);
        } else {
            sortModelComprador.setRowFilter(RowFilter.regexFilter(txtComprador, 0));
        }
    }

    private void seleccionComprador() {
        tableCompradores.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {  // evita doble disparo
                int fila = tableCompradores.getSelectedRow();

                if (fila >= 0) {
                    int id = (int) tableCompradores.getValueAt(fila, 0);
                    System.out.println("Fila seleccionada. ID: " + id);

                    Comprador comprador = compradorDAO.buscarComprador(id);
                    if (comprador != null) {
                        txtNombre.setText(comprador.getNombre());
                        txtDNI.setText(String.valueOf(comprador.getDni()));
                        txtPassword.setText(comprador.getPassword());
                        dateChooserFecha.setDate(java.sql.Date.valueOf(comprador.getFechaNac()));
                        comboBoxPago.setSelectedItem(comprador.getMedioPago());
                    }
                }
            }
        });
    }
    
    private void limpiarCampos() {
        txtIDComprador.setText("");
        txtDNI.setText("");
        txtNombre.setText("");
        txtPassword.setText("");
        comboBoxPago.setSelectedItem(-1);
        dateChooserFecha.setDate(null);

    }

    public compradorVista(SistemaCine sc) {
        initComponents();
        tableCompradores.setDefaultEditor(Object.class, null);
        //tableCompradores.setRowSelectionAllowed(false);
        //tableCompradores.setCellSelectionEnabled(false);
        llenarTableCompradores();
        filtrarCompradores();
        buttonGuardarCambios.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGuardar = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dateChooserFecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        comboBoxPago = new javax.swing.JComboBox<>();
        txtDNI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCompradores = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtIDComprador = new javax.swing.JTextField();
        buttonGuardarCambios = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(795, 600));

        jLabel1.setText("GESTION DE CLIENTES");

        buttonGuardar.setText("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        buttonModificar.setText("Modificar");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Contraseña:");

        jLabel4.setText("Nombre:");

        jLabel7.setText("Fecha de Nacimiento:");

        jLabel8.setText("Medio de Pago:");

        comboBoxPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Transferencia", "Tarjeta" }));

        jLabel3.setText("DNI:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxPago, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tableCompradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "DNI", "Fecha de Nacimiento", "Pago"
            }
        ));
        jScrollPane1.setViewportView(tableCompradores);

        jLabel6.setText("Buscar Cliente por ID:");

        txtIDComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDCompradorActionPerformed(evt);
            }
        });

        buttonGuardarCambios.setText("Guardar Cambios");
        buttonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(buttonGuardarCambios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonEliminar))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(buttonGuardar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(buttonGuardar)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonModificar)
                    .addComponent(buttonEliminar)
                    .addComponent(jLabel6)
                    .addComponent(txtIDComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGuardarCambios))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        if (txtDNI.getText().isEmpty() || txtPassword.getText().isEmpty() || txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.");
            return;
        }

        if (dateChooserFecha.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Seleccione una fecha valida.");
            return;
        }

        if (comboBoxPago.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un metodo de pago.");
            return;
        }

        int dni = 0;
        String nombre = txtNombre.getText();
        String contra = (txtPassword.getText());
        LocalDate fecha = dateChooserFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String medioPago = comboBoxPago.getSelectedItem().toString();

        try {
            dni = Integer.parseInt(txtDNI.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un formato valido para campo numerico.");
            return;
        }

        Comprador comprador = new Comprador(dni, nombre, contra, medioPago, fecha);

        compradorDAO.guardarComprador(comprador);

        limpiarCampos();
        llenarTableCompradores();

    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        if (tableCompradores.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un cliente de la lista.");
        }
        tableCompradores.setRowSelectionAllowed(true);
        seleccionComprador();
        buttonGuardar.setEnabled(false);
        buttonGuardarCambios.setEnabled(true);

    }//GEN-LAST:event_buttonModificarActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed



    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void jbnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnuevoActionPerformed

        limpiarCampos();
        txtIDComprador.setText("");
        txtIDComprador.setEditable(false);
    }//GEN-LAST:event_jbnuevoActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed

    }//GEN-LAST:event_jbsalirActionPerformed

    private void txtIDCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDCompradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCompradorActionPerformed

    private void buttonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarCambiosActionPerformed
        if (tableCompradores.getSelectedRow() >= 0) {

            if (txtDNI.getText().isEmpty() || txtPassword.getText().isEmpty() || txtNombre.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.");
                return;
            }

            if (dateChooserFecha.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Seleccione una fecha valida.");
                return;
            }

            int id = (int) tableCompradores.getValueAt(tableCompradores.getSelectedRow(), 0);
            int dni = 0;
            String nombre = txtNombre.getText();
            String contra = (txtPassword.getText());
            LocalDate fecha = dateChooserFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            String medioPago = comboBoxPago.getSelectedItem().toString();

            try {
                dni = Integer.parseInt(txtDNI.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese formato valido para campo numerico");
                return;
            }

            Comprador comprador = new Comprador(id, dni, nombre, contra, medioPago, fecha);

            compradorDAO.modificarComprador(comprador);
            llenarTableCompradores();
            limpiarCampos();
            buttonGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_buttonGuardarCambiosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonGuardarCambios;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JComboBox<String> comboBoxPago;
    private com.toedter.calendar.JDateChooser dateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCompradores;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtIDComprador;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables

}
