/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Conexion;
import Modelo.Lugar;
import Modelo.Pelicula;
import Modelo.Proyeccion;
import Modelo.Sala;
import Persistencia.CompradorData;
import Persistencia.LugarData;
import Persistencia.PeliculaData;
import Persistencia.ProyeccionData;
import Persistencia.SalaData;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 * S
 *
 * @author Usuario
 */
public class ProyeccionVista extends javax.swing.JInternalFrame {

    private SistemaCine sistemaCine = new SistemaCine();

    private Conexion conex = sistemaCine.conexionDb();
    private LugarData lugarDAO = new LugarData(conex);
    private ProyeccionData proyeccionDAO = new ProyeccionData(conex);

    DefaultTableModel modeloTableProyeccion;
    TableRowSorter<DefaultTableModel> sortModelProyeccion;
    ListSelectionListener selectorLista;

    private void llenarTableProyeccion() {

        DocumentListener listenerFiltro = new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                filtrarProyeccion();
            }

            public void removeUpdate(DocumentEvent e) {
                filtrarProyeccion();
            }

            public void changedUpdate(DocumentEvent e) {
                filtrarProyeccion();
            }
        };

        List<Proyeccion> listaProyeccion = proyeccionDAO.listarProyeccion();

        tableProyecciones.setShowGrid(false);
        modeloTableProyeccion = (DefaultTableModel) tableProyecciones.getModel();
        modeloTableProyeccion.setRowCount(0);

        for (Proyeccion pro : listaProyeccion) {
            modeloTableProyeccion.addRow(new Object[]{
                pro.getIdProyeccion(),
                pro.getPelicula(),
                pro.getSala(),
                pro.getIdioma(),
                pro.isEs3D(),
                pro.isSubtitulada(),
                pro.getHoraInicio(),
                pro.getHoraFin(),
                pro.getPrecio(),
                pro.isActiva(),
                    pro.getFecha()
            });
        }

        sortModelProyeccion = new TableRowSorter<>(modeloTableProyeccion);
        tableProyecciones.setRowSorter(sortModelProyeccion);
        txtProyeccionID.getDocument().addDocumentListener(listenerFiltro);
    }

    private void filtrarProyeccion() {
        String txtIDBuscar = txtProyeccionID.getText().trim();
        if (txtIDBuscar.isEmpty()) {
            sortModelProyeccion.setRowFilter(null);
        } else {
            sortModelProyeccion.setRowFilter(RowFilter.regexFilter(txtIDBuscar, 0));
        }
    }

    public ProyeccionVista(SistemaCine sc) {
        initComponents();
        tableProyecciones.setDefaultEditor(Object.class, null);
        cargarPelicula();
        cargarSala();
        llenarTableProyeccion();
        filtrarProyeccion();
        buttonGuardarCambios.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGuardar = new javax.swing.JButton();
        buttonGuardarCambios = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtIdioma = new javax.swing.JTextField();
        comboBoxSala = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        comboBoxPelicula = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        radioButton3D = new javax.swing.JCheckBox();
        radioButtonSub = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtHoraFin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtHoraInicio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        radioButtonActiva = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        fecha1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProyecciones = new javax.swing.JTable();
        buttonEliminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtProyeccionID = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setText("Gestion de Proyecciones");

        buttonGuardar.setText("Guardar");
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });

        buttonGuardarCambios.setText("Guardar Cambios");
        buttonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarCambiosActionPerformed(evt);
            }
        });

        buttonModificar.setText("Modificar");
        buttonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Pelicula:");

        comboBoxSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSalaActionPerformed(evt);
            }
        });

        jLabel6.setText("Sala:");

        jLabel3.setText("Idioma:");

        radioButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonSubActionPerformed(evt);
            }
        });

        jLabel4.setText("Subitiulada:");

        jLabel7.setText("3D:");

        jLabel10.setText("Precio:");

        jLabel9.setText("Hora Fin:");

        txtHoraInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraInicioActionPerformed(evt);
            }
        });

        jLabel8.setText("Hora Inicio:");

        radioButtonActiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActivaActionPerformed(evt);
            }
        });

        jLabel2.setText("Activa:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonSub)
                    .addComponent(radioButton3D)
                    .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoraInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButtonActiva)
                            .addComponent(txtHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboBoxPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboBoxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radioButton3D)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(radioButtonSub)
                            .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(radioButtonActiva))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableProyecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Pelicula", "Sala", "Idioma", "3D", "Subtitulada", "Hora Inicio", "Hora Fin", "Precio", "Activa"
            }
        ));
        jScrollPane1.setViewportView(tableProyecciones);

        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        jLabel11.setText("Buscar Proyeccion por ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProyeccionID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonGuardarCambios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonModificar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))))
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(buttonGuardar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonGuardar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonGuardarCambios)
                    .addComponent(buttonModificar)
                    .addComponent(buttonEliminar)
                    .addComponent(jLabel11)
                    .addComponent(txtProyeccionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSalaActionPerformed

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        String idioma = txtIdioma.getText();
        if (idioma.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar el idioma ");
            txtIdioma.requestFocus();
            return;
        }

        Proyeccion p;
        Pelicula pe = (Pelicula) comboBoxPelicula.getSelectedItem();
        Sala sa = (Sala) comboBoxSala.getSelectedItem();

        boolean es3d = radioButton3D.isSelected();
        boolean subtitulada = radioButtonSub.isSelected();

        try {
            double precio = Double.parseDouble(txtPrecio.getText());
            if (precio <= 0) {
                JOptionPane.showMessageDialog(null, "El precio debe ser mayor a 0.");
                txtPrecio.requestFocus();
                return;
            }

            if (txtHoraInicio.getText().isEmpty() || txtHoraFin.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "debe ingresar la hora");
                return;
            }

            DateTimeFormatter formato = DateTimeFormatter.ofPattern("HH:mm");
            LocalTime inicio = LocalTime.parse(txtHoraInicio.getText(), formato);

            LocalTime fin = LocalTime.parse(txtHoraFin.getText(), formato);
            if (fin.isBefore(inicio)) {
                JOptionPane.showMessageDialog(null, " ingrese la hora correctamente");
                return;
            }
            boolean activa = true;
LocalDate f = fecha1.getDate().toInstant()
                          .atZone(ZoneId.systemDefault())
                          .toLocalDate();

            p = new Proyeccion(pe, sa, idioma, es3d, subtitulada, inicio, fin, precio, activa,f);

            ProyeccionData proyeccionDAO = new ProyeccionData(conex);
            proyeccionDAO.agregarProyeccion(p);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ingrese un numero valido");
        } catch (Exception o) {
            JOptionPane.showMessageDialog(null, "ingrese la hora correctamente");
        }
        limpiar();
        llenarTableProyeccion();
    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void buttonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarCambiosActionPerformed

        if (tableProyecciones.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una proyección para modificar.");
            return;
        }

        if (comboBoxPelicula.getSelectedItem() == null
                || comboBoxSala.getSelectedItem() == null
                || txtIdioma.getText().isEmpty()
                || txtPrecio.getText().isEmpty()
                || txtHoraInicio.getText().isEmpty()
                || txtHoraFin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios.");
            return;
        }

        int idProyeccion = (int) tableProyecciones.getValueAt(tableProyecciones.getSelectedRow(), 0);

        Pelicula peli = (Pelicula) comboBoxPelicula.getSelectedItem();
        Sala sala = (Sala) comboBoxSala.getSelectedItem();

        String idioma = txtIdioma.getText();
        boolean es3D = radioButton3D.isSelected();
        boolean subtitulada = radioButtonSub.isSelected();
        boolean activa = radioButtonActiva.isSelected();

        double precio;
        LocalTime horaInicio, horaFin;

        try {
            precio = Double.parseDouble(txtPrecio.getText());
            horaInicio = LocalTime.parse(txtHoraInicio.getText());
            horaFin = LocalTime.parse(txtHoraFin.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Revisar formatos precio (numerico) y horas (HH:mm)");
            return;
        }
       LocalDate f = fecha1.getDate().toInstant()
                          .atZone(ZoneId.systemDefault())
                          .toLocalDate();

        Proyeccion pro = new Proyeccion(idProyeccion, peli, sala, idioma, es3D, subtitulada, horaInicio, horaFin, precio, activa);

        ProyeccionData proyeccionDAO = new ProyeccionData(conex);
        proyeccionDAO.modificarProyeccion(pro);

        llenarTableProyeccion();

        limpiar();

        if (selectorLista != null) {
            tableProyecciones.getSelectionModel().removeListSelectionListener(selectorLista);
            selectorLista = null;
        }

        buttonGuardarCambios.setEnabled(false);
        buttonGuardar.setEnabled(true);

        JOptionPane.showMessageDialog(null, "Proyección actualizada correctamente.");
    }//GEN-LAST:event_buttonGuardarCambiosActionPerformed

    private void radioButtonActivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonActivaActionPerformed

    }//GEN-LAST:event_radioButtonActivaActionPerformed

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed

        if (tableProyecciones.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione una proyección de la lista.");
            return;
        }

        selectorLista = e -> {
            if (!e.getValueIsAdjusting()) {

                int fila = tableProyecciones.getSelectedRow();
                if (fila < 0) {
                    return;
                }

                int idProy = (int) tableProyecciones.getValueAt(fila, 0);
                Pelicula peli = (Pelicula) tableProyecciones.getValueAt(fila, 1);
                Sala sala = (Sala) tableProyecciones.getValueAt(fila, 2);
                String idioma = (String) tableProyecciones.getValueAt(fila, 3);
                boolean es3D = (Boolean) tableProyecciones.getValueAt(fila, 4);
                boolean subtitulada = (Boolean) tableProyecciones.getValueAt(fila, 5);
                LocalTime horaInicio = (LocalTime) tableProyecciones.getValueAt(fila, 6);
                LocalTime horaFin = (LocalTime) tableProyecciones.getValueAt(fila, 7);
                double precio = (Double) tableProyecciones.getValueAt(fila, 8);
                boolean activa = (Boolean) tableProyecciones.getValueAt(fila, 9);

                for (int i = 0; i < comboBoxPelicula.getItemCount(); i++) {
                    Pelicula item = comboBoxPelicula.getItemAt(i);
                    if (item.getIdPelicula() == peli.getIdPelicula()) {
                        comboBoxPelicula.setSelectedIndex(i);
                        break;
                    }
                }

                for (int i = 0; i < comboBoxSala.getItemCount(); i++) {
                    Sala item = comboBoxSala.getItemAt(i);
                    if (item.getIdSala() == sala.getIdSala()) {
                        comboBoxSala.setSelectedIndex(i);
                        break;
                    }
                }

                txtIdioma.setText(idioma);
                txtPrecio.setText(String.valueOf(precio));
                txtHoraInicio.setText(String.valueOf(horaInicio));
                txtHoraFin.setText(String.valueOf(horaFin));

                radioButton3D.setSelected(es3D);
                radioButtonSub.setSelected(subtitulada);
                radioButtonActiva.setSelected(activa);

                System.out.println("Cargando datos de proyección ID: " + idProy);
            }
        };

        tableProyecciones.getSelectionModel().addListSelectionListener(selectorLista);

        buttonGuardar.setEnabled(false);
        buttonGuardarCambios.setEnabled(true);


    }//GEN-LAST:event_buttonModificarActionPerformed

    private void radioButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonSubActionPerformed

    private void txtHoraInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraInicioActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed

        if (tableProyecciones.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione una proyeccion de la lista.");
            return;
        }

        int id = (int) tableProyecciones.getValueAt(tableProyecciones.getSelectedRow(), 0);

        Object[] opciones = {"Si", "No"};

        int resultado = JOptionPane.showOptionDialog(rootPane, "¿Seguro que desea eliminar la proyeccion?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        ProyeccionData proyeccionDAO = new ProyeccionData(conex);
        if (resultado == 0) {
            proyeccionDAO.eliminarProyeccion(id);
        }

        llenarTableProyeccion();
    

    }//GEN-LAST:event_buttonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonGuardarCambios;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JComboBox<Pelicula> comboBoxPelicula;
    private javax.swing.JComboBox<Sala> comboBoxSala;
    private com.toedter.calendar.JDateChooser fecha1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox radioButton3D;
    private javax.swing.JCheckBox radioButtonActiva;
    private javax.swing.JCheckBox radioButtonSub;
    private javax.swing.JTable tableProyecciones;
    private javax.swing.JTextField txtHoraFin;
    private javax.swing.JTextField txtHoraInicio;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProyeccionID;
    // End of variables declaration//GEN-END:variables
public void cargarPelicula() {
        PeliculaData peliDAO = new PeliculaData(conex);
        List<Pelicula> listaPelis = peliDAO.listarPeliculasEnCartelera();
        DefaultComboBoxModel<Pelicula> modelo = new DefaultComboBoxModel<>();
        for (Pelicula peli : listaPelis) {
            modelo.addElement(peli);
        }
        comboBoxPelicula.setModel(modelo);
    }

    public void cargarSala() {
        SalaData salaDAO = new SalaData(conex);
        List<Sala> listaSala = salaDAO.listarSalasActivas();
        DefaultComboBoxModel<Sala> modelo = new DefaultComboBoxModel<>();
        for (Sala sala : listaSala) {
            modelo.addElement(sala);
        }
        comboBoxSala.setModel(modelo);
    }

    public void limpiar() {
        txtIdioma.setText("");
        txtPrecio.setText("");
        txtHoraInicio.setText("");
        txtHoraFin.setText("");
        radioButton3D.setSelected(false);
        radioButtonSub.setSelected(false);
        comboBoxPelicula.setSelectedIndex(-1);
        comboBoxSala.setSelectedIndex(-1);

    }

}
