/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Conexion;
import Modelo.Pelicula;
import Modelo.Proyeccion;
import Modelo.Sala;
import Persistencia.CompradorData;
import Persistencia.PeliculaData;
import Persistencia.ProyeccionData;
import Persistencia.SalaData;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * S
 *
 * @author Usuario
 */
public class proyeccionVista extends javax.swing.JInternalFrame {

    private SistemaCine sc;

    private Conexion con;

    private ProyeccionData pd;
    private PeliculaData ped;
    private SalaData sd;

    /**
     * Creates new form proyeccionVista
     */
    private List<Pelicula> p;
    private List<Sala> s;

    public proyeccionVista(SistemaCine sc) {
        initComponents();
        this.sc = sc;
        this.con = sc.conexionDb();
        this.pd = new ProyeccionData(con);
        this.ped = new PeliculaData(con);
        this.sd = new SalaData(con);

        cargarPelicula();
        cargarSala();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbguardar = new javax.swing.JButton();
        jbnuevo = new javax.swing.JButton();
        jbmodificar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtidioma = new javax.swing.JTextField();
        txtsala = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtpelicula = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtes3d = new javax.swing.JCheckBox();
        txtsubtitulada = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txthorafin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txthorainicio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtactivar = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setText("Gestion de Proyecciones");

        jbguardar.setText("Guardar");
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });

        jbnuevo.setText("Guardar Cambios");
        jbnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnuevoActionPerformed(evt);
            }
        });

        jbmodificar.setText("Modificar");
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Pelicula:");

        txtsala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalaActionPerformed(evt);
            }
        });

        jLabel6.setText("Sala:");

        jLabel3.setText("Idioma:");

        txtsubtitulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubtituladaActionPerformed(evt);
            }
        });

        jLabel4.setText("Subitiulada:");

        jLabel7.setText("3D:");

        jLabel10.setText("Precio:");

        jLabel9.setText("Hora Fin:");

        txthorainicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorainicioActionPerformed(evt);
            }
        });

        jLabel8.setText("Hora Inicio:");

        txtactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtactivarActionPerformed(evt);
            }
        });

        jLabel2.setText("Activa:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubtitulada)
                    .addComponent(txtes3d)
                    .addComponent(txtidioma, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txthorainicio, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtactivar)
                            .addComponent(txthorafin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtpelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtsala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthorainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtidioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthorafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtes3d)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtsubtitulada)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtactivar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Buscar Proyeccion por ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(308, 308, 308))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbnuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbmodificar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))))
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(jbguardar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbguardar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnuevo)
                    .addComponent(jbmodificar)
                    .addComponent(jButton1)
                    .addComponent(jLabel11)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalaActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed

        String idioma = txtidioma.getText();

        if (idioma.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar el idioma ");
            txtidioma.requestFocus();
            return;
        }

        Proyeccion p;
        Pelicula pe = (Pelicula) txtpelicula.getSelectedItem();
        Sala sa = (Sala) txtsala.getSelectedItem();

        boolean es3d = txtes3d.isSelected();
        boolean subtitulada = txtsubtitulada.isSelected();

        try {
            double precio = Double.parseDouble(txtprecio.getText());
            if (precio <= 0) {
                JOptionPane.showMessageDialog(null, "El precio debe ser mayor a 0.");
                txtprecio.requestFocus();
                return;
            }

            if (txthorainicio.getText().isEmpty() || txthorafin.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "debe ingresar la hora");
                return;
            }

            DateTimeFormatter formato = DateTimeFormatter.ofPattern("HH:mm");
            LocalTime inicio = LocalTime.parse(txthorainicio.getText(), formato);

            LocalTime fin = LocalTime.parse(txthorafin.getText(), formato);
            if (fin.isBefore(inicio)) {
                JOptionPane.showMessageDialog(null, " ingrese la hora correctamente");
                return;
            }
            boolean activa = true;

            p = new Proyeccion(pe, sa, idioma, es3d, subtitulada, inicio, fin, precio, activa);

            pd.agregarProyeccion(p);
            limpiar();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ingrese un numero valido");
        } catch (Exception o) {
            JOptionPane.showMessageDialog(null, "ingrese la hora correctamente");
        }
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jbnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnuevoActionPerformed

    }//GEN-LAST:event_jbnuevoActionPerformed

    private void txtactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtactivarActionPerformed

    }//GEN-LAST:event_txtactivarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed

        Pelicula pe = (Pelicula) txtpelicula.getSelectedItem();
        Sala sa = (Sala) txtsala.getSelectedItem();
        try {
            boolean es3d = txtes3d.isSelected();
            boolean subtitulada = txtsubtitulada.isSelected();

            double precio = Double.parseDouble(txtprecio.getText());
            if (precio <= 0) {
                JOptionPane.showMessageDialog(null, "El precio debe ser mayor a 0.");
                txtprecio.requestFocus();
                return;
            }

            if (txthorainicio.getText().isEmpty() || txthorafin.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "debe ingresar la hora");

            }
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("HH:mm");
            LocalTime inicio = LocalTime.parse(txthorainicio.getText(), formato);

            LocalTime fin = LocalTime.parse(txthorafin.getText(), formato);
            if (fin.isBefore(inicio)) {
                JOptionPane.showMessageDialog(null, " ingrese la hora correctamente");
                return;
            }
            boolean activa = txtactivar.isSelected();
            String idioma = txtidioma.getText();

            if (idioma.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar el idioma ");
                txtidioma.requestFocus();
                return;
            }

            Proyeccion pr = new Proyeccion(pe, sa, idioma, es3d, subtitulada, inicio, fin, precio, activa);

            pr.setIdProyeccion();
            pd.modificarProyeccion(pr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ingrese un numero valido");
        } catch (Exception o) {
            JOptionPane.showMessageDialog(null, "ingrese la hora correctamente");
        }


    }//GEN-LAST:event_jbmodificarActionPerformed

    private void txtsubtituladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubtituladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubtituladaActionPerformed

    private void txthorainicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorainicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorainicioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jbmodificar;
    private javax.swing.JButton jbnuevo;
    private javax.swing.JCheckBox txtactivar;
    private javax.swing.JCheckBox txtes3d;
    private javax.swing.JTextField txthorafin;
    private javax.swing.JTextField txthorainicio;
    private javax.swing.JTextField txtidioma;
    private javax.swing.JComboBox<Pelicula> txtpelicula;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JComboBox<Sala> txtsala;
    private javax.swing.JCheckBox txtsubtitulada;
    // End of variables declaration//GEN-END:variables
public void cargarPelicula() {
        p = ped.listarPeliculasEnCartelera();
        DefaultComboBoxModel<Pelicula> modelo = new DefaultComboBoxModel<>();
        for (Pelicula peli : p) {
            modelo.addElement(peli);
        }
        txtpelicula.setModel(modelo);
    }

    public void cargarSala() {
        s = sd.listarSalasActivas();

        DefaultComboBoxModel<Sala> modelo = new DefaultComboBoxModel<>();
        for (Sala sala : s) {
            modelo.addElement(sala);

        }
        txtsala.setModel(modelo);

    }

    public void limpiar() {
        txtidioma.setText("");
        txtprecio.setText("");
        txthorainicio.setText("");
        txthorafin.setText("");
        txtes3d.setSelected(false);
        txtsubtitulada.setSelected(false);
        txtpelicula.setSelectedIndex(-1);
        txtsala.setSelectedIndex(-1);

    }

}
