/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Conexion;
import Modelo.Pelicula;
import Modelo.Proyeccion;
import Modelo.Sala;
import Persistencia.CompradorData;
import Persistencia.PeliculaData;
import Persistencia.ProyeccionData;
import Persistencia.SalaData;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *S
 * @author Usuario
 */
public class proyeccionVista extends javax.swing.JInternalFrame {
private  SistemaCine sc;

private Conexion con ;


private ProyeccionData pd;
private PeliculaData ped;
private SalaData sd;



    /**
     * Creates new form proyeccionVista
     */
    private List<Pelicula> p;
    private List<Sala>s;
    public proyeccionVista(SistemaCine sc) {
        initComponents();
        this.sc=sc;
        this.con=sc.conexionDb();
        this.pd=new ProyeccionData(con);
         this.ped = new PeliculaData(con);    
         this.sd=new SalaData(con);
        
        
        
        
        
        
        
        
        cargarPelicula();
       cargarSala();
       txtid.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpelicula = new javax.swing.JComboBox<>();
        txtsala = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtes3d = new javax.swing.JCheckBox();
        txtsubtitulada = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jbguardar = new javax.swing.JButton();
        jbdarbaja = new javax.swing.JButton();
        jbnuevo = new javax.swing.JButton();
        jbmodificar = new javax.swing.JButton();
        jbbuscar = new javax.swing.JButton();
        txtactivar = new javax.swing.JCheckBox();
        txtidioma = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txthorainicio = new javax.swing.JTextField();
        txthorafin = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jbsalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 2, 24)); // NOI18N
        jLabel1.setText("Proyeccion");

        jLabel2.setText("ID:");

        txtsala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalaActionPerformed(evt);
            }
        });

        jLabel3.setText("idioma");

        jLabel5.setText("Pelicula");

        jLabel6.setText("Sala");

        txtes3d.setText("es 3D?");

        txtsubtitulada.setText("subtitulada");

        jLabel8.setText("Hora inicio");

        jLabel9.setText("Hora fin");

        jLabel10.setText("precio");

        jbguardar.setText("guardar");
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });

        jbdarbaja.setText("dar baja");
        jbdarbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdarbajaActionPerformed(evt);
            }
        });

        jbnuevo.setText("nuevo");
        jbnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnuevoActionPerformed(evt);
            }
        });

        jbmodificar.setText("modificar");
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });

        jbbuscar.setText("buscar");
        jbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarActionPerformed(evt);
            }
        });

        txtactivar.setText("Activar");
        txtactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtactivarActionPerformed(evt);
            }
        });

        jbsalir.setText("salir");
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtpelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel6))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtsala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtidioma, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(txtsubtitulada, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtes3d)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel10))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txthorafin, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(216, 216, 216)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txthorainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jbnuevo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbguardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbdarbaja)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbmodificar)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtactivar)
                            .addComponent(jbbuscar)
                            .addComponent(jbsalir))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtpelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbbuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtsala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(txtidioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtes3d)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsubtitulada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthorainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txthorafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtactivar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnuevo)
                    .addComponent(jbguardar)
                    .addComponent(jbdarbaja)
                    .addComponent(jbmodificar)
                    .addComponent(jbsalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalaActionPerformed

    private void jbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscarActionPerformed
        txtid.setEnabled(true);
  
       
      Proyeccion p=  pd.buscarProyeccion(Integer.parseInt(txtid.getText()));
      if (p == null) {
    JOptionPane.showMessageDialog(this, "No existe la proyección con ese ID.");
    return;
}
      txtpelicula.setSelectedItem(p.getPelicula());
      txtsala.setSelectedItem(p.getSala());
      txtidioma.setText(p.getIdioma());
      txtes3d.setSelected(p.isEs3D());
      txtsubtitulada.setSelected(p.isSubtitulada());
      txthorainicio.setText(p.getHoraInicio().toString()) ;
      txthorafin.setText(p.getHoraFin().toString());
      txtprecio.setText(String.valueOf(p.getPrecio()));
      
    }//GEN-LAST:event_jbbuscarActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed
      
        String idioma=txtidioma.getText();
        
        if (idioma.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar el idioma ");
            txtidioma.requestFocus();
            return;
        }
        
        Proyeccion p;
       Pelicula pe=(Pelicula) txtpelicula.getSelectedItem();
       Sala sa=(Sala) txtsala.getSelectedItem();
       
       boolean es3d=txtes3d.isSelected();
       boolean subtitulada=txtsubtitulada.isSelected();
       
       try{
       double precio=Double.parseDouble(txtprecio.getText());
      if (precio <= 0) {
                JOptionPane.showMessageDialog(null, "El precio debe ser mayor a 0.");
                txtprecio.requestFocus();
                return;}
       
       if(txthorainicio.getText().isEmpty()||txthorafin.getText().isEmpty()){
         JOptionPane.showMessageDialog(null, "debe ingresar la hora");
       return;
       }
       
       DateTimeFormatter formato = DateTimeFormatter.ofPattern("HH:mm");
       LocalTime inicio=LocalTime.parse(txthorainicio.getText(),formato);
      
      LocalTime fin=LocalTime.parse(txthorafin.getText(),formato);
       if(fin.isBefore(inicio)){
           JOptionPane.showMessageDialog(null, " ingrese la hora correctamente");
           return;
       }
       boolean activa=true;
       
       p=new Proyeccion(pe,sa,idioma,es3d,subtitulada,inicio,fin,precio,activa);
      
       pd.agregarProyeccion(p);
       limpiar();
       txtid.setText("");
        }catch(NumberFormatException e){
       JOptionPane.showMessageDialog(null, "ingrese un numero valido");
       }catch(Exception o){
       JOptionPane.showMessageDialog(null, "ingrese la hora correctamente");
       }
    }//GEN-LAST:event_jbguardarActionPerformed

    private void jbnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnuevoActionPerformed
        limpiar();
        txtid.setText("");
        txtid.setEditable(false);
    }//GEN-LAST:event_jbnuevoActionPerformed

    private void jbdarbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdarbajaActionPerformed
       
       txtid.setEditable(true);
       if(txtid.getText()==null){
           
           JOptionPane.showMessageDialog(null, "ingrese el id de la proyeccion q desea dar de baja");
           return;
       };
       try{
       pd.bajaLogica(Integer.parseInt(txtid.getText()));
        }catch(Exception e){JOptionPane.showMessageDialog(null, "no se a encontrado nada"); }
        txtid.setText("");
        txtid.setEditable(false);
        limpiar();
    }//GEN-LAST:event_jbdarbajaActionPerformed

    private void txtactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtactivarActionPerformed
        
    }//GEN-LAST:event_txtactivarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed
     
        Pelicula pe=(Pelicula) txtpelicula.getSelectedItem();
       Sala sa=(Sala) txtsala.getSelectedItem();
       try{
       boolean es3d=txtes3d.isSelected();
       boolean subtitulada=txtsubtitulada.isSelected();
       
       
       double precio=Double.parseDouble(txtprecio.getText());
      if (precio <= 0) {
                JOptionPane.showMessageDialog(null, "El precio debe ser mayor a 0.");
                txtprecio.requestFocus();
                return;}
       
       if(txthorainicio.getText().isEmpty()||txthorafin.getText().isEmpty()){
         JOptionPane.showMessageDialog(null, "debe ingresar la hora");
       
       }
       
       DateTimeFormatter formato = DateTimeFormatter.ofPattern("HH:mm");
       LocalTime inicio=LocalTime.parse(txthorainicio.getText(),formato);
      
      LocalTime fin=LocalTime.parse(txthorafin.getText(),formato);
       if(fin.isBefore(inicio)){
           JOptionPane.showMessageDialog(null, " ingrese la hora correctamente");
           return;
       }
       boolean activa=txtactivar.isSelected();
         String idioma=txtidioma.getText();
        
        if (idioma.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar el idioma ");
            txtidioma.requestFocus();
            return;
        }
        
        
       
       

        

Proyeccion pr=new Proyeccion(pe,sa,idioma,es3d,subtitulada,inicio,fin,precio,activa);

  pr.setIdProyeccion(Integer.parseInt(txtid.getText()));
        pd.modificarProyeccion(pr);
         }catch(NumberFormatException e){
       JOptionPane.showMessageDialog(null, "ingrese un numero valido");
       }catch(Exception o){
       JOptionPane.showMessageDialog(null, "ingrese la hora correctamente");
       }
        
        
    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbbuscar;
    private javax.swing.JButton jbdarbaja;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jbmodificar;
    private javax.swing.JButton jbnuevo;
    private javax.swing.JButton jbsalir;
    private javax.swing.JCheckBox txtactivar;
    private javax.swing.JCheckBox txtes3d;
    private javax.swing.JTextField txthorafin;
    private javax.swing.JTextField txthorainicio;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidioma;
    private javax.swing.JComboBox<Pelicula> txtpelicula;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JComboBox<Sala> txtsala;
    private javax.swing.JCheckBox txtsubtitulada;
    // End of variables declaration//GEN-END:variables
public void cargarPelicula() {
    p = ped.listarPeliculasEnCartelera();
    DefaultComboBoxModel<Pelicula> modelo = new DefaultComboBoxModel<>();
    for (Pelicula peli : p) {
        modelo.addElement(peli);
    }
    txtpelicula.setModel(modelo);
}

public void cargarSala(){
s=sd.listarSalasActivas();

 DefaultComboBoxModel<Sala>modelo=new DefaultComboBoxModel<>();
for(Sala sala: s){
modelo.addElement(sala);

}
txtsala.setModel(modelo);


}


public void limpiar() {
    txtid.setText("");
    txtidioma.setText("");
    txtprecio.setText("");
    txthorainicio.setText("");
    txthorafin.setText("");
    txtes3d.setSelected(false);
    txtsubtitulada.setSelected(false);
    txtpelicula.setSelectedIndex(-1); 
    txtsala.setSelectedIndex(-1);  
    
}


}

