/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Comprador;
import Modelo.Conexion;
import Modelo.Sala;
import Persistencia.SalaData;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class salaVista extends javax.swing.JInternalFrame {
private  SistemaCine sc;
private Conexion con;
private SalaData sd;

    /**
     * Creates new form salaVista
     */
    public salaVista(SistemaCine sc) {
        initComponents();
        
        this.sc=sc;
        this.con=sc.conexionDb();
        this.sd=new SalaData(con);
        
        
        txtid.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbnuevo = new javax.swing.JButton();
        jbguardar = new javax.swing.JButton();
        jbmodificar = new javax.swing.JButton();
        jbeliminar = new javax.swing.JButton();
        jbbuscar = new javax.swing.JButton();
        txtapta3d = new javax.swing.JCheckBox();
        txtactiva = new javax.swing.JCheckBox();
        txtid = new javax.swing.JTextField();
        txtnrosala = new javax.swing.JTextField();
        txtcapacidad = new javax.swing.JTextField();
        jbsalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel1.setText("sala");

        jLabel2.setText("ID");

        jLabel3.setText("nroSala");

        jLabel5.setText("capacidad");

        jbnuevo.setText("nuevo");
        jbnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnuevoActionPerformed(evt);
            }
        });

        jbguardar.setText("guardar");
        jbguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbguardarActionPerformed(evt);
            }
        });

        jbmodificar.setText("modificar");
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });

        jbeliminar.setText("dar baja");
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });

        jbbuscar.setText("buscar");
        jbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarActionPerformed(evt);
            }
        });

        txtapta3d.setText("apta3D");

        txtactiva.setText("activa");
        txtactiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtactivaActionPerformed(evt);
            }
        });

        jbsalir.setText("salir");
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbbuscar)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 116, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnrosala, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbnuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbguardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbmodificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbeliminar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtapta3d)
                            .addComponent(txtactiva, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbsalir)
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnrosala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jbbuscar)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtactiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtapta3d)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbnuevo)
                            .addComponent(jbguardar)
                            .addComponent(jbmodificar)
                            .addComponent(jbeliminar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jbsalir)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnuevoActionPerformed
       limpiar();
       txtid.setText("");
        txtid.setEditable(false);
    }//GEN-LAST:event_jbnuevoActionPerformed

    private void jbguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbguardarActionPerformed
      Sala s;
      
      if(txtnrosala.getText().isEmpty()||txtcapacidad.getText().isEmpty()){
      JOptionPane.showMessageDialog(null, "campos vacios!");
      return;
      };
      try{
      int nrosala=Integer.parseInt(txtnrosala.getText());
      boolean apta3d=txtapta3d.isSelected();
      int capacidad=Integer.parseInt(txtcapacidad.getText());
      boolean estado=txtactiva.isSelected();
      
      
      
      s=new Sala(nrosala,apta3d,capacidad,estado);
      sd.guardarSala(s);
      JOptionPane.showMessageDialog(null, "Sala guardada ");
      }catch(NumberFormatException e){
       JOptionPane.showMessageDialog(null, "deben ingresar valores numericos");
      
      }
      limpiar();
      txtid.setText("");
    }//GEN-LAST:event_jbguardarActionPerformed

    private void txtactivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtactivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtactivaActionPerformed

    private void jbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscarActionPerformed
      try{
        txtid.setEditable(true);
         if(txtid.getText().isEmpty()){
           
           JOptionPane.showMessageDialog(this, "debe ingresar un id");
           return;
           } 
        
        int id=Integer.parseInt(txtid.getText());
            
      Sala s= sd.buscarSala(id);
      
      
      if (s == null) {
    JOptionPane.showMessageDialog(this, "No existe la sala con ese ID");
    return;
}
        txtid.setText(s.getIdSala()+"");
        txtnrosala.setText(s.getNroSala()+"");
        txtapta3d.setSelected(s.isApta3D());
        txtcapacidad.setText(s.getCapacidad()+"");
        txtactiva.setSelected(s.getEstado());
       
      }catch(Exception e){
          JOptionPane.showMessageDialog(this, "error, vuelva a intentar");
      }
    }//GEN-LAST:event_jbbuscarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed
    
        Sala s;
       if(txtnrosala.getText().isEmpty()||txtcapacidad.getText().isEmpty()){
      JOptionPane.showMessageDialog(null, "campos vacios!");
      return;
      };
        
      try{  
        int nrosala=Integer.parseInt(txtnrosala.getText());
         boolean apta3d=txtapta3d.isSelected();
         int capacidad=Integer.parseInt(txtcapacidad.getText());
          boolean estado= txtactiva.isSelected();
          s=new Sala(nrosala,apta3d,capacidad,estado);
           s.setIdSala(Integer.parseInt(txtid.getText()));
          sd.modificarSala(s);
      }catch(NumberFormatException e){
       JOptionPane.showMessageDialog(null, "deben ingresar valores numericos");
      
      }
          limpiar();
          txtid.setText("");
          
    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed
txtid.setEnabled(true);


        if(txtid.getText().isEmpty()){
        
        JOptionPane.showMessageDialog(null, "ingrese el id de la sala que  desea dar de baja");
        return;
        }
        try{
        int id=Integer.parseInt(txtid.getText());
        Sala sala= sd.buscarSala(id);
        if(sala==null){
        JOptionPane.showMessageDialog(null, "no hay ninguna sala con ese ID");
        return;
        }else{
         sd.bajaLogicaSala(id);
        
        }
        
      
      
       txtid.setText("");
        txtid.setEnabled(false);
       limpiar();
       
        }catch(NumberFormatException e){
        
          JOptionPane.showMessageDialog(null, "ingrese un valor numerico");
          return;
        }
       
      
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbbuscar;
    private javax.swing.JButton jbeliminar;
    private javax.swing.JButton jbguardar;
    private javax.swing.JButton jbmodificar;
    private javax.swing.JButton jbnuevo;
    private javax.swing.JButton jbsalir;
    private javax.swing.JCheckBox txtactiva;
    private javax.swing.JCheckBox txtapta3d;
    private javax.swing.JTextField txtcapacidad;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnrosala;
    // End of variables declaration//GEN-END:variables
private void limpiar() {
        
       txtid.setText("");
        txtnrosala.setText("");
        txtapta3d.setSelected(false);
        txtcapacidad.setText("");
       txtactiva.setSelected(false);
        
       
        

    }
}
