/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelo.Conexion;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author PC1
 */
public class SistemaCine extends javax.swing.JFrame {

    /**
     * Creates new form SistemaCine
     */
    public SistemaCine() {

        initComponents();
        setLocationRelativeTo(null);
        setSize(800, 600);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        menuBar4 = new java.awt.MenuBar();
        menu7 = new java.awt.Menu();
        menu8 = new java.awt.Menu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        escritorio1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuticket = new javax.swing.JMenu();
        menusala = new javax.swing.JMenuItem();
        menucomprador = new javax.swing.JMenuItem();
        menuproyeccion = new javax.swing.JMenuItem();
        Lugar = new javax.swing.JMenuItem();
        jmenuticket = new javax.swing.JMenuItem();
        menupelicula = new javax.swing.JMenuItem();
        jventa = new javax.swing.JMenu();
        menuonline = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu6.setText("jMenu6");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        menu7.setLabel("File");
        menuBar4.add(menu7);

        menu8.setLabel("Edit");
        menuBar4.add(menu8);

        jMenu1.setText("File");
        jMenuBar3.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar3.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));

        escritorio1.setMinimumSize(new java.awt.Dimension(800, 800));
        escritorio1.setPreferredSize(new java.awt.Dimension(1500, 1200));
        escritorio1.add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 670);

        getContentPane().add(escritorio1, java.awt.BorderLayout.CENTER);

        menuticket.setText("gestor");
        menuticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuticketActionPerformed(evt);
            }
        });

        menusala.setText("salas");
        menusala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusalaActionPerformed(evt);
            }
        });
        menuticket.add(menusala);

        menucomprador.setText("compradores");
        menucomprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucompradorActionPerformed(evt);
            }
        });
        menuticket.add(menucomprador);

        menuproyeccion.setText("proyeccion");
        menuproyeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuproyeccionActionPerformed(evt);
            }
        });
        menuticket.add(menuproyeccion);

        Lugar.setText("Lugar");
        Lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LugarActionPerformed(evt);
            }
        });
        menuticket.add(Lugar);

        jmenuticket.setText("ticket");
        jmenuticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuticketActionPerformed(evt);
            }
        });
        menuticket.add(jmenuticket);

        menupelicula.setText("Peliculas");
        menupelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupeliculaActionPerformed(evt);
            }
        });
        menuticket.add(menupelicula);

        jMenuBar1.add(menuticket);

        jventa.setText("venta");

        menuonline.setText("Venta Online");
        menuonline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuonlineActionPerformed(evt);
            }
        });
        jventa.add(menuonline);

        jMenuBar1.add(jventa);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menupeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupeliculaActionPerformed
        escritorio1.removeAll();
        escritorio1.repaint();

        peliculaVista GUI = new peliculaVista(this);
        GUI.setVisible(true);

        escritorio1.add(GUI);
        escritorio1.moveToFront(GUI);

        GUI.setBorder(null);
        ((BasicInternalFrameUI) GUI.getUI()).setNorthPane(null);
    
    }//GEN-LAST:event_menupeliculaActionPerformed

    private void menuproyeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuproyeccionActionPerformed
        escritorio1.removeAll();
        escritorio1.repaint();

        proyeccionVista GUI = new proyeccionVista(this);
        GUI.setVisible(true);

        escritorio1.add(GUI);
        escritorio1.moveToFront(GUI);

        GUI.setBorder(null);
        ((BasicInternalFrameUI) GUI.getUI()).setNorthPane(null);

    }//GEN-LAST:event_menuproyeccionActionPerformed

    private void menucompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucompradorActionPerformed
        escritorio1.removeAll();
        escritorio1.repaint();

        compradorVista GUI = new compradorVista(this);
        GUI.setVisible(true);

        escritorio1.add(GUI);
        escritorio1.moveToFront(GUI);

        GUI.setBorder(null);
        ((BasicInternalFrameUI) GUI.getUI()).setNorthPane(null);
    }//GEN-LAST:event_menucompradorActionPerformed

    private void menusalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusalaActionPerformed
        escritorio1.removeAll();
        escritorio1.repaint();

        salaVista GUI = new salaVista(this);
        GUI.setVisible(true);

        escritorio1.add(GUI);
        escritorio1.moveToFront(GUI);
    }//GEN-LAST:event_menusalaActionPerformed

    private void menuticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuticketActionPerformed

    }//GEN-LAST:event_menuticketActionPerformed

    private void jmenuticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuticketActionPerformed
        VentaPresencial gui = new VentaPresencial(this);
        escritorio1.moveToFront(gui);
        escritorio1.removeAll();
        escritorio1.repaint();

        escritorio1.add(gui);
        gui.setVisible(true);

        gui.setBorder(null);
        ((BasicInternalFrameUI) gui.getUI()).setNorthPane(null);

    }//GEN-LAST:event_jmenuticketActionPerformed

    private void LugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LugarActionPerformed
        escritorio1.removeAll();
        escritorio1.repaint();
        lugarVista gui = new lugarVista(this);
        gui.setVisible(true);
        escritorio1.add(gui);
        escritorio1.moveToFront(gui);
    }//GEN-LAST:event_LugarActionPerformed

    private void menuonlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuonlineActionPerformed
        VentaOnline gui = new VentaOnline(this);
escritorio1.removeAll();
escritorio1.add(gui);
gui.setVisible(true);
escritorio1.moveToFront(gui);

    }//GEN-LAST:event_menuonlineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaCine.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaCine.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaCine.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaCine.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaCine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Lugar;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JDesktopPane escritorio1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmenuticket;
    private javax.swing.JMenu jventa;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.Menu menu7;
    private java.awt.Menu menu8;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private java.awt.MenuBar menuBar4;
    private javax.swing.JMenuItem menucomprador;
    private javax.swing.JMenuItem menuonline;
    private javax.swing.JMenuItem menupelicula;
    private javax.swing.JMenuItem menuproyeccion;
    private javax.swing.JMenuItem menusala;
    private javax.swing.JMenu menuticket;
    // End of variables declaration//GEN-END:variables

    public Conexion conexionDb() {
        Conexion conn = new Conexion("gp9_cinemacentro_basededatos", "jdbc:mariadb://localhost/", "root", "", "org.mariadb.jdbc.Driver");
        return conn;
    }
}
